export const dayMapping: Record<string, string> = {
  Domingo: '1',
  'Segunda-feira': '2',
  'Terça-feira': '3',
  'Quarta-feira': '4',
  'Quinta-feira': '5',
  'Sexta-feira': '6',
  Sábado: '7',
};

export const dayOptions = [
  { value: '', text: 'Selecione o Dia da Semana' },
  { value: 'Domingo', text: 'Domingo' },
  { value: 'Segunda-feira', text: 'Segunda-feira' },
  { value: 'Terça-feira', text: 'Terça-feira' },
  { value: 'Quarta-feira', text: 'Quarta-feira' },
  { value: 'Quinta-feira', text: 'Quinta-feira' },
  { value: 'Sexta-feira', text: 'Sexta-feira' },
  { value: 'Sábado', text: 'Sábado' },
];

export const tipoOptions = [
  { value: '', text: 'Selecione um Curso' },
  { value: 'SM_PROG', text: 'Super Módulo Programação' },
  { value: 'SM_CR', text: 'Super Módulo Criativos' },
  { value: 'WK', text: 'Workshop' },
  { value: 'DD', text: 'Design Full Stack' },
  { value: 'DFS', text: 'Programação FullStack' },
  { value: 'DS', text: 'Data Science' },
  { value: 'MD', text: 'Marketing' },
  { value: 'PHD', text: 'Fotografia' },
  { value: 'FILM', text: 'Film Desing' },
];

export const moduloOptions: Record<string, { value: string; text: string }[]> =
  {
    WK: [
      { value: '', text: 'Selecione um Módulo' },
      { value: 'Tema Livre', text: 'Tema Livre' },
    ],
    DFS: [
      { value: '', text: 'Selecione um Módulo' },
      { value: 'Lógica de Programação', text: 'Lógica de Programação' },
      { value: 'Python', text: 'Python' },
      { value: 'HTML/CSS', text: 'HTML/CSS' },
      { value: 'Javascript', text: 'Javascript' },
    ],
    DS: [
      { value: '', text: 'Selecione um Módulo' },
      { value: 'Lógica de Programação', text: 'Lógica de Programação' },
      { value: 'Python', text: 'Python' },
      { value: 'Data Science Pro', text: 'Data Science Pro' },
    ],
    MD: [
      { value: '', text: 'Selecione um Módulo' },
      { value: 'Marketing Descomplicado', text: 'Marketing Descomplicado' },
      { value: 'Design Fácil', text: 'Design Fácil' },
      { value: 'Redes Sociais na Prática', text: 'Redes Sociais na Prática' },
      {
        value: 'Landing Page para Tráfego Pago',
        text: 'Landing Page para Tráfego Pago',
      },
      { value: 'Anúncios no META', text: 'Anúncios no META' },
      { value: 'Visibilidade no Google', text: 'Visibilidade no Google' },
      { value: 'Anúncios no Google', text: 'Anúncios no Google' },
    ],
    PHD: [
      { value: '', text: 'Selecione um Módulo' },
      {
        value: 'Fotografia para Iniciantes',
        text: 'Fotografia para Iniciantes',
      },
      { value: 'Fotografia em Ação', text: 'Fotografia em Ação' },
      { value: 'Dominando Fotografia', text: 'Dominando Fotografia' },
      { value: 'Edição com Lightroom', text: 'Edição com Lightroom' },
      {
        value: 'Edição Avançada no Photoshop',
        text: 'Edição Avançada no Photoshop',
      },
    ],
    DD: [
      { value: '', text: 'Selecione um Módulo' },
      { value: 'Introdução à Fotografia', text: 'Introdução à Fotografia' },
      { value: 'Edição com Photoshop', text: 'Edição com Photoshop' },
      { value: 'Arte com Illustrator', text: 'Arte com Illustrator' },
      { value: 'Criação com IA', text: 'Criação com IA' },
      { value: 'Editando Vídeos', text: 'Editando Vídeos' },
      { value: 'Finalização de Vídeos', text: 'Finalização de Vídeos' },
      { value: 'Interface Criativa', text: 'Interface Criativa' },
    ],
    FILM: [
      { value: '', text: 'Selecione um Módulo' },
      { value: 'Contando Histórias com IA', text: 'Contando Histórias com IA' },
      { value: 'Criação Visual com IA', text: 'Criação Visual com IA' },
      { value: 'Filmagem Básica', text: 'Filmagem Básica' },
      {
        value: 'Filmagem de alta performance',
        text: 'Filmagem de alta performance',
      },
      { value: 'Vídeos de Impacto', text: 'Vídeos de Impacto' },
      { value: 'Finalização de Vídeos', text: 'Finalização de Vídeos' },
      { value: 'Trabalhando com Áudio', text: 'Trabalhando com Áudio' },
    ],
    SM_PROG: [
      { value: '', text: 'Selecione um Módulo' },
      { value: 'Node JS', text: 'Node JS' },
      { value: 'HTML/CSS(Avançado)', text: 'HTML/CSS(Avançado)' },
      { value: 'FastAPI', text: 'FastAPI' },
      { value: 'Power BI', text: 'Power BI' },
      { value: 'React JS', text: 'React JS' },
      { value: 'React Native', text: 'React Native' },
      { value: 'Flask', text: 'Flask' },
      { value: 'Git/Github', text: 'Git/Github' },
      { value: 'Automação e IA', text: 'Automação e IA' },
      { value: 'Data Science', text: 'Data Science' },
      { value: 'Django', text: 'Django' },
      { value: 'Banco de Dados', text: 'Banco de Dados' },
    ],
    SM_CR: [
      { value: '', text: 'Selecione um Módulo' },
      { value: 'MKT 5.0 Design Thinking', text: 'MKT 5.0 Design Thinking' },
      { value: 'Creative Code UX/UI', text: 'Creative Code UX/UI' },
      { value: 'Desenvolvimento Low Code', text: 'Desenvolvimento Low Code' },
      { value: 'Google Analytics', text: 'Google Analytics' },
      { value: 'Metodologias Ágeis', text: 'Metodologias Ágeis' },
      { value: 'Facebook ADS', text: 'Facebook ADS' },
      { value: 'Direção de Arte', text: 'Direção de Arte' },
      { value: 'Photoshop (Avançado)', text: 'Photoshop (Avançado)' },
      { value: 'Fotografia (Avançado)', text: 'Fotografia (Avançado)' },
      { value: 'Iluminação (Avançado)', text: 'Iluminação (Avançado)' },
      {
        value: 'Captura de Vídeo (Avançado)',
        text: 'Captura de Vídeo (Avançado)',
      },
      { value: 'Animação de Marca', text: 'Animação de Marca' },
      { value: 'TikTok', text: 'TikTok' },
      { value: 'CRM Marketing', text: 'CRM Marketing' },
      { value: 'Redação Publicitária', text: 'Redação Publicitária' },
      { value: 'InDesign', text: 'InDesign' },
      {
        value: 'Narrativas Audiovisuais (Avançado)',
        text: 'Narrativas Audiovisuais (Avançado)',
      },
      { value: 'Design de Marca', text: 'Design de Marca' },
    ],
  };
